status = [
    "Build (x86_64-unknown-linux-gnu)",
    "Build (x86_64-unknown-linux-musl)",
    "Build (i686-unknown-linux-gnu)",
    "Build (i686-unknown-linux-musl)",
    "Build (aarch64-unknown-linux-gnu)",
    "Build (aarch64-unknown-linux-musl)",
    "Build (armv5te-unknown-linux-gnueabi)",
    "Build (armv7-unknown-linux-gnueabihf)",
    "Build (arm-unknown-linux-gnueabi)",
    "Build (arm-unknown-linux-gnueabihf)",
    "Build (riscv64gc-unknown-linux-gnu)",
    "Test",
    "Lint",
]
required_approvals = 1
up_to_date_approvals = true
delete_merged_branches = true
update_base_for_deletes = true
use_codeowners = true
use_squash_merge = true
commit_title = "Merge ${PR_REFS}"
timeout_sec = 36000
